package de.zeeman.sayingDb.data;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Authors generated by hbm2java
 */
public class Author implements java.io.Serializable {
	private final SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
	private static final long serialVersionUID = -5377780433725915520L;
	private int id;
	private Picture picture;
	private String lastname;
	private String firstname;
	private Date birthday;
	private Date obit;
	private String work;
	private Set<Saying> sayings = new HashSet<Saying>(0);

	public Author() {
	}

	public Author(int id, String lastname, String firstname) {
		this.id = id;
		this.lastname = lastname;
		this.firstname = firstname;
	}

	public Author(int id, Picture pictures, String lastname,
			String firstname, Date birthday, Date obit, String work,
			Set<Saying> sayings) {
		this.id = id;
		this.picture = pictures;
		this.lastname = lastname;
		this.firstname = firstname;
		this.birthday = birthday;
		this.obit = obit;
		this.work = work;
		this.sayings = sayings;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Picture getPicture() {
		return this.picture;
	}

	public void setPicture(Picture picture) {
		this.picture = picture;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getObit() {
		return this.obit;
	}

	public void setObit(Date obit) {
		this.obit = obit;
	}

	public String getWork() {
		return this.work;
	}

	public void setWork(String work) {
		this.work = work;
	}

	public Set<Saying> getSayings() {
		return this.sayings;
	}

	public void setSayings(Set<Saying> sayings) {
		this.sayings = sayings;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((birthday == null) ? 0 : birthday.hashCode());
		result = prime * result
				+ ((firstname == null) ? 0 : firstname.hashCode());
		result = prime * result + id;
		result = prime * result
				+ ((lastname == null) ? 0 : lastname.hashCode());
		result = prime * result + ((obit == null) ? 0 : obit.hashCode());
		result = prime * result
				+ ((picture == null) ? 0 : picture.hashCode());
		result = prime * result
				+ ((sayings == null) ? 0 : sayings.hashCode());
		result = prime * result + ((work == null) ? 0 : work.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Author))
			return false;
		final Author other = (Author) obj;
		if (birthday == null) {
			if (other.birthday != null)
				return false;
		} else if (!birthday.equals(other.birthday))
			return false;
		if (firstname == null) {
			if (other.firstname != null)
				return false;
		} else if (!firstname.equals(other.firstname))
			return false;
		if (id != other.id)
			return false;
		if (lastname == null) {
			if (other.lastname != null)
				return false;
		} else if (!lastname.equals(other.lastname))
			return false;
		if (obit == null) {
			if (other.obit != null)
				return false;
		} else if (!obit.equals(other.obit))
			return false;
		if (picture == null) {
			if (other.picture != null)
				return false;
		} else if (!picture.equals(other.picture))
			return false;
		if (sayings == null) {
			if (other.sayings != null)
				return false;
		} else if (!sayings.equals(other.sayings))
			return false;
		if (work == null) {
			if (other.work != null)
				return false;
		} else if (!work.equals(other.work))
			return false;
		return true;
	}
	
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append(getLastname());
		sb.append(",");
		sb.append(getFirstname());
		sb.append(" ( *").append( sdf.format(getBirthday()) );
		if (getObit() != null) {
			sb.append(" - \u271d");
			sb.append( sdf.format(getObit()) );
		}
		sb.append(")");
		
		return sb.toString();
	}

	public String getName() {
		StringBuffer sb = new StringBuffer();
		sb.append(getLastname()).append(", ").append(getFirstname());
		return sb.toString();
	}
	

}
