package de.zeeman.sayingDb.data;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

/**
 * Pictures generated by hbm2java
 */
public class Picture implements java.io.Serializable {

	private static final long serialVersionUID = -6541285778888065474L;
	private int id;
	private byte[] data;
	private int length;
	private String mime;
	private Set<Author> authors = new HashSet<Author>(0);

	public Picture() {
	}

	public Picture(int id, byte[] data, int length, String mime) {
		this.id = id;
		this.data = data;
		this.length = length;
		this.mime = mime;
	}

	public Picture(int id, byte[] data, int length, String mime,
			Set<Author> authors) {
		this.id = id;
		this.data = data;
		this.length = length;
		this.mime = mime;
		this.authors = authors;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public byte[] getData() {
		return this.data;
	}

	public void setData(byte[] data) {
		this.data = data;
	}

	public int getLength() {
		return this.length;
	}

	public void setLength(int length) {
		this.length = length;
	}

	public String getMime() {
		return this.mime;
	}

	public void setMime(String mime) {
		this.mime = mime;
	}

	public Set<Author> getAuthors() {
		return this.authors;
	}

	public void setAuthorses(Set<Author> authors) {
		this.authors = authors;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((authors == null) ? 0 : authors.hashCode());
		result = prime * result + Arrays.hashCode(data);
		result = prime * result + id;
		result = prime * result + length;
		result = prime * result + ((mime == null) ? 0 : mime.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Picture))
			return false;
		final Picture other = (Picture) obj;
		if (authors == null) {
			if (other.authors != null)
				return false;
		} else if (!authors.equals(other.authors))
			return false;
		if (!Arrays.equals(data, other.data))
			return false;
		if (id != other.id)
			return false;
		if (length != other.length)
			return false;
		if (mime == null) {
			if (other.mime != null)
				return false;
		} else if (!mime.equals(other.mime))
			return false;
		return true;
	}
	
	

}
