package de.zeeman.sayingDb.data;

/**
 * Sayings generated by hbm2java
 */
public class Saying implements java.io.Serializable {

	private static final long serialVersionUID = -1088654860851975299L;
	private int id;
	private Author author;
	private String saying;

	public Saying() {
	}

	public Saying(int id, Author author, String saying) {
		this.id = id;
		this.author = author;
		this.saying = saying;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	public String getSaying() {
		return this.saying;
	}

	public void setSaying(String saying) {
		this.saying = saying;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((author == null) ? 0 : author.hashCode());
		result = prime * result + id;
		result = prime * result + ((saying == null) ? 0 : saying.hashCode());
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (!(obj instanceof Saying))
			return false;
		final Saying other = (Saying) obj;
		if (author == null) {
			if (other.author != null)
				return false;
		} else if (!author.equals(other.author))
			return false;
		if (id != other.id)
			return false;
		if (saying == null) {
			if (other.saying != null)
				return false;
		} else if (!saying.equals(other.saying))
			return false;
		return true;
	}
	
	public String toString() {
		StringBuffer sb = new StringBuffer();
		
		sb.append(getSaying());
		
		if (getAuthor() != null) {
			sb.append(" [").append(getAuthor().toString()).append("]");
		}
		
		return sb.toString();
	}

}
